### ISSUE TITLE
Is it possible with EdenRed Spain?

### ISSUE THREAD

**Issue by SoyDiego** [josecoelhomelo/edenred-transactions#1]
Hi Jose, I tried to use adding https://edenred.es/ and https://clientes.edenred.es/ but doesn't work.
Do you know if is possible using for Edenred Spain or what is the correct host/version?

Thanks and good work!!

**Comment by josecoelhomelo** [comment]
Hi Diego, https://clientes.edenred.es is the right link but I'm afraid their API structure is different, I'd have to analyze the whole process while having access to an account. Let me know if you're interested in working together with that. Cheers.

**Comment by SoyDiego** [comment]
> 

Hi Jose, I would like to do that. My intention is create something very easy. I can tell you later :)
How can I be in contact with you? Are you in a community of Discord or something like that?

Thanks for you reply!

**Comment by josecoelhomelo** [comment]
Sure, add me there: @josecoelhomelo
